version: "3.8"
services:
  otelcol:
    image: otel/opentelemetry-collector:0.47.0
    ports:
      - "4317:4317"
      - "4318:4318"
      - "55678:55678"
      - "55679:55679"
    volumes:
      - ".github/otel-test-config.yaml:/otel-local-config.yaml"
    command: ["--config", "otel-local-config.yaml"]
    links:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.31.0
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
